services:
  api:
    build: ./api
    ports:
      - "8008:8000"
    environment:
    - "MONGO_DB_USERNAME=enersense-assignment"
    - "MONGO_DB_PASSWORD=D5lvIenxIjXiIESa"
  publisher:
    build: ./publisher
    environment:
    - "BROKER_HOST=broker.hivemq.com"
    - "BROKER_PORT=1883"
  listener:
    build: ./listener
    environment:
    - "BROKER_HOST=broker.hivemq.com"
    - "BROKER_PORT=1883"
    - "MONGO_DB_USERNAME=enersense-assignment"
    - "MONGO_DB_PASSWORD=D5lvIenxIjXiIESa"

